### ISSUE TITLE
Modifier le titre de l'onglet "Tableaux_de_bord_ISO"

### ISSUE THREAD

**Issue by pcanon** [pcanon/BCED-ARTEMIS#21]
L'onglet "Tableaux de bord ISO" présente la même vue Radar que l'onglet "Radar Business"
Il doit donc porter le même nom
Supprimer l'onglet "Radar ISO", qui est redondant avec l'onglet "Tableau de bord ISO"

**Comment by ahoubaille** [comment]
l'onglet "Tableaux de bord ISO" a été renommé en "Radar ISO" et l'ancien onglet "Radar ISO" a été renommé "dashbord ISO" et est caché maintenant.
