### ISSUE TITLE
Bug dans macro "Traitement" lorsque aucun risque à traiter

### ISSUE THREAD

**Issue by pcanon** [pcanon/BCED-ARTEMIS#33]
Lorsque il n'y a aucun risque à traiter, c'est-à-dire que le niveau du risque de la menace est en dessous du niveau de tolérance au risque , la macro traitement dans l'onglet "Cartographie_M" se crashe en raison de l'absence d'une condition relative à la vérification du traitement.

**Comment by ahoubaille** [comment]
Fait
